### ISSUE TITLE
got an error when connecting sqlserver 2008r2

### ISSUE THREAD

**Issue by buddynotshotme** [awaragi/prometheus-mssql-exporter#40] opened 2022-04-25 08:54 UTC
022-04-25T07:48:56.229Z app Prometheus-MSSQL Exporter listening on local port 4000 monitoring sa@testsql.com:1433
2022-04-25T07:49:00.515Z app Received /metrics request
Failed to connect to database: Failed to connect to testsql.com:1433 - Could not connect (sequence)
2022-04-25T07:49:00.808Z app Error handling /metrics request
/usr/src/app/index.js:132
    mssql_up.set(0);
    ^

ReferenceError: mssql_up is not defined
    at /usr/src/app/index.js:132:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by awaragi** [comment] 2022-04-25 11:54
I see the problem. I will fix quickly but the root cause is that your database is down or unreachable .

**Comment by awaragi** [comment] 2022-04-25 12:10
@buddynotshotme  Problem fixed in 1.2.1. Please give it another shot.

**Closed by awaragi** 2022-04-25 12:10 UTC

**Comment by buddynotshotme** [comment] 2022-04-26 06:00
well,The problem can be solved.
i think the root cause is that tls is setted incorrectly.
---------------------------------------------------------
encrypt: false, trustServerCertificate: false,
